[/]
visible-name='Juliana'

use-theme-colors=false
foreground-color='#d8dee9'
background-color='#000000'

use-theme-cursor-colors=false
cursor-colors-set=true
cursor-background-color='#fac761'
cursor-foreground-color='#2e353e'

palette=['#303841', '#ec5f66', '#99c794', '#fac761', '#5c99d6', '#c695c6', '#5fb4b4', '#d8dee9', '#46525c', '#c76b70', '#99c794', '#f9ae58', '#95b2d6', '#c695c6', '#87c7c7', '#ffffff']

bold-is-bright=true
use-system-font=false
font='Hack 18'
audible-bell=false

