vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "fl4my_cold"
local hi = function(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end
-- base
hi("normal",        { fg = "#8fa0b3", bg = "#0d1117" })
hi("normalnc",      { bg = "#0d1117" })
hi("signcolumn",    { bg = "#0d1117" })
hi("endofbuffer",   { fg = "#21262d", bg = "#0d1117" })
-- cursor & line
hi("cursorline",    { bg = "NONE" })
-- hi("cursorline",    { bg = "#161b22" })
hi("cursorlinenr",  { fg = "#8fa0b3", bold = true, bg = "#0d1117" })
hi("linenr",        { fg = "#3d444d", bg = "#0d1117" })
-- ui
hi("statusline",    { bg = "#161b22", fg = "#58a6ff", bold = true })
hi("statuslinenc",  { bg = "#0d1117", fg = "#3d444d" })
hi("winseparator",  { fg = "#21262d" })
hi("visual",        { bg = "#1f2d3d" })
hi("search",        { fg = "#0d1117", bg = "#58a6ff" })
hi("incsearch",     { fg = "#0d1117", bg = "#ffa657" })
hi("matchparen",    { fg = "#d2a8ff", bold = true })
-- pmenu
hi("pmenu",         { fg = "#8fa0b3", bg = "#161b22" })
hi("pmenusel",      { fg = "#0d1117", bg = "#58a6ff" })
-- syntax fallback
hi("comment",       { fg = "#3d444d", italic = true })
hi("string",        { fg = "#a5d6ff" })
hi("number",        { fg = "#ffa657" })
hi("boolean",       { fg = "#79c0ff" })
hi("keyword",       { fg = "#ff7b72" })
hi("conditional",   { fg = "#ff7b72" })
hi("repeat",        { fg = "#ff7b72" })
hi("statement",     { fg = "#ff7b72" })
hi("function",      { fg = "#d2a8ff", bold = true })
hi("identifier",    { fg = "#8fa0b3" })
hi("type",          { fg = "#79c0ff" })
hi("operator",      { fg = "#79c0ff" })
hi("special",       { fg = "#79c0ff" })
hi("preproc",       { fg = "#58a6ff" })
hi("delimiter",     { fg = "#8b949e" })
-- treesitter
hi("@keyword",                     { fg = "#ff7b72" })
hi("@keyword.conditional",         { fg = "#ff7b72" })
hi("@keyword.function",            { fg = "#ff7b72" })
hi("@keyword.return",              { fg = "#ff7b72" })
hi("@keyword.import",              { fg = "#58a6ff" })
hi("@keyword.repeat",              { fg = "#ff7b72" })
hi("@keyword.exception",           { fg = "#ff7b72" })
hi("@function",                    { fg = "#d2a8ff", bold = true })
hi("@function.call",               { fg = "#d2a8ff" })
hi("@function.builtin",            { fg = "#d2a8ff", bold = true })
hi("@function.method",             { fg = "#d2a8ff" })
hi("@method",                      { fg = "#d2a8ff" })
hi("@method.call",                 { fg = "#d2a8ff" })
hi("@variable",                    { fg = "#8fa0b3" })
hi("@parameter",                   { fg = "#8fa0b3" })
hi("@string",                      { fg = "#a5d6ff" })
hi("@string.escape",               { fg = "#79c0ff" })
hi("@number",                      { fg = "#ffa657" })
hi("@boolean",                     { fg = "#79c0ff" })
hi("@comment",                     { fg = "#3d444d", italic = true })
hi("@operator",                    { fg = "#79c0ff" })
hi("@punctuation.bracket",         { fg = "#8b949e" })
hi("@punctuation.delimiter",       { fg = "#8b949e" })
hi("@type",                        { fg = "#79c0ff" })
hi("@type.builtin",                { fg = "#79c0ff" })
hi("@constant",                    { fg = "#8fa0b3" })
hi("@constant.builtin",            { fg = "#79c0ff" })
hi("@attribute",                   { fg = "#ff7b72" })
vim.opt.cursorline = false
