vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "fl4my"
local hi = function(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end
-- base
hi("normal",        { fg = "#d0d0ff", bg = "#200020" })
hi("normalnc",      { bg = "#200020" })
hi("signcolumn",    { bg = "#200020" })
hi("endofbuffer",   { fg = "#3a1a3a", bg = "#200020" })
-- cursor & line
hi("cursorline",    { bg = "#2d002d" })
hi("cursorlinenr",  { fg = "#d0d0ff", bold = true, bg = "#200020" })
hi("linenr",        { fg = "#5a3a5a", bg = "#200020" })
-- ui
hi("statusline",    { bg = "#2d002d", fg = "#8888cc", bold = true })
hi("statuslinenc",  { bg = "#200020", fg = "#5a3a5a" })
hi("winseparator",  { fg = "#3a1a3a" })
hi("visual",        { bg = "#3d1a4a" })
hi("search",        { fg = "#200020", bg = "#d0d0ff" })
hi("incsearch",     { fg = "#200020", bg = "#e3b341" })
hi("matchparen",    { fg = "#fe89fb", bold = true })
-- pmenu
hi("pmenu",         { fg = "#d0d0ff", bg = "#2d002d" })
hi("pmenusel",      { fg = "#200020", bg = "#d0d0ff" })
-- syntax fallback
hi("comment",       { fg = "#6666aa", italic = true })
hi("string",        { fg = "#e3b341" })
hi("number",        { fg = "#e3b341" })
hi("boolean",       { fg = "#b47fcb" })
hi("keyword",       { fg = "#b47fcb" })
hi("conditional",   { fg = "#b47fcb" })
hi("repeat",        { fg = "#b47fcb" })
hi("statement",     { fg = "#b47fcb" })
hi("function",      { fg = "#d0d0ff", bold = true })
hi("identifier",    { fg = "#d0d0ff" })
hi("type",          { fg = "#fe89fb" })
hi("operator",      { fg = "#a0a0dd" })
hi("special",       { fg = "#a0a0dd" })
hi("preproc",       { fg = "#3b858b" })
hi("delimiter",     { fg = "#a0a0dd" })
-- treesitter
hi("@keyword",                     { fg = "#b47fcb" })
hi("@keyword.conditional",         { fg = "#b47fcb" })
hi("@keyword.function",            { fg = "#b47fcb" })
hi("@keyword.return",              { fg = "#b47fcb" })
hi("@keyword.import",              { fg = "#3b858b" })
hi("@keyword.repeat",              { fg = "#b47fcb" })
hi("@keyword.exception",           { fg = "#b47fcb" })
hi("@function",                    { fg = "#d0d0ff", bold = true })
hi("@function.call",               { fg = "#d0d0ff" })
hi("@function.builtin",            { fg = "#d0d0ff", bold = true })
hi("@function.method",             { fg = "#d0d0ff" })
hi("@method",                      { fg = "#d0d0ff" })
hi("@method.call",                 { fg = "#d0d0ff" })
hi("@variable",                    { fg = "#d0d0ff" })
hi("@parameter",                   { fg = "#c0c0ee" })
hi("@string",                      { fg = "#e3b341" })
hi("@string.escape",               { fg = "#e3b341" })
hi("@number",                      { fg = "#e3b341" })
hi("@boolean",                     { fg = "#b47fcb" })
hi("@comment",                     { fg = "#6666aa", italic = true })
hi("@operator",                    { fg = "#a0a0dd" })
hi("@punctuation.bracket",         { fg = "#a0a0dd" })
hi("@punctuation.delimiter",       { fg = "#a0a0dd" })
hi("@type",                        { fg = "#fe89fb" })
hi("@type.builtin",                { fg = "#fe89fb" })
hi("@constant",                    { fg = "#d0d0ff" })
hi("@constant.builtin",            { fg = "#fe89fb" })
hi("@attribute",                   { fg = "#b47fcb" })
vim.opt.cursorline = false
