vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
  vim.cmd("syntax reset")
end
vim.g.colors_name = "fl4my_green"
local hi = function(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

-- PALETTE
-- bg:             #0C0D21  dark navy
-- fg:             #76b28f  normal green
-- keyword_bright: #b07bc4  bright purple
-- keyword_dim:    #855492  dim purple
-- import:         #3E7580  teal
-- string/number:  #D8A06A  orange
-- comment:        #16E519  bright green
-- dim:            #1e1f35  slightly lighter bg

hi("Normal",        { fg = "#76b28f", bg = "#0C0D21" })
hi("NormalNC",      { bg = "#0C0D21" })
hi("SignColumn",    { bg = "#0C0D21" })
hi("EndOfBuffer",   { fg = "#1e1f35", bg = "#0C0D21" })
hi("CursorLine",    { bg = "NONE" })
hi("CursorLineNr",  { fg = "#76b28f", bold = true, bg = "#0C0D21" })
hi("LineNr",        { fg = "#2a2b45", bg = "#0C0D21" })
hi("StatusLine",    { bg = "#13142e", fg = "#76b28f", bold = true })
hi("StatusLineNC",  { bg = "#0C0D21", fg = "#2a2b45" })
hi("WinSeparator",  { fg = "#1e1f35" })
hi("Visual",        { bg = "#1e2a35" })
hi("Search",        { fg = "#0C0D21", bg = "#76b28f" })
hi("IncSearch",     { fg = "#0C0D21", bg = "#D8A06A" })
hi("MatchParen",    { fg = "#b07bc4", bold = true })
hi("Pmenu",         { fg = "#76b28f", bg = "#13142e" })
hi("PmenuSel",      { fg = "#0C0D21", bg = "#76b28f" })
hi("DiagnosticError",   { fg = "#ff5555" })
hi("DiagnosticWarn",    { fg = "#D8A06A" })
hi("DiagnosticInfo",    { fg = "#76b28f" })
hi("DiagnosticHint",    { fg = "#3E7580" })
hi("Comment",       { fg = "#16E519", italic = true })
hi("String",        { fg = "#D8A06A" })
hi("Number",        { fg = "#D8A06A" })
hi("Float",         { fg = "#D8A06A" })
hi("Boolean",       { fg = "#D8A06A" })
hi("Keyword",       { fg = "#b07bc4" })
hi("Conditional",   { fg = "#b07bc4" })
hi("Repeat",        { fg = "#b07bc4" })
hi("Statement",     { fg = "#855492" })
hi("Exception",     { fg = "#855492" })
hi("Function",      { fg = "#76b28f", bold = true })
hi("Identifier",    { fg = "#76b28f" })
hi("Type",          { fg = "#76b28f" })
hi("Operator",      { fg = "#76b28f" })
hi("Special",       { fg = "#76b28f" })
hi("Delimiter",     { fg = "#76b28f" })
hi("PreProc",       { fg = "#3E7580" })
hi("Include",       { fg = "#3E7580" })
hi("SpecialChar",   { fg = "#D8A06A" })
hi("@keyword",                     { fg = "#b07bc4" })
hi("@keyword.conditional",         { fg = "#b07bc4" })
hi("@keyword.function",            { fg = "#b07bc4" })
hi("@keyword.return",              { fg = "#855492" })
hi("@keyword.import",              { fg = "#3E7580" })
hi("@keyword.repeat",              { fg = "#b07bc4" })
hi("@keyword.exception",           { fg = "#855492" })
hi("@keyword.operator",            { fg = "#b07bc4" })
hi("@keyword.coroutine",           { fg = "#b07bc4" })
hi("@function",                    { fg = "#76b28f", bold = true })
hi("@function.call",               { fg = "#76b28f", bold = true })
hi("@function.builtin",            { fg = "#76b28f", bold = true })
hi("@function.method",             { fg = "#76b28f", bold = true })
hi("@method",                      { fg = "#76b28f", bold = true })
hi("@method.call",                 { fg = "#76b28f", bold = true })
hi("@variable",                    { fg = "#76b28f" })
hi("@variable.builtin",            { fg = "#76b28f" })
hi("@parameter",                   { fg = "#76b28f" })
hi("@string",                      { fg = "#D8A06A" })
hi("@string.escape",               { fg = "#D8A06A" })
hi("@number",                      { fg = "#D8A06A" })
hi("@float",                       { fg = "#D8A06A" })
hi("@boolean",                     { fg = "#D8A06A" })
hi("@comment",                     { fg = "#16E519", italic = true })
hi("@operator",                    { fg = "#76b28f" })
hi("@punctuation.bracket",         { fg = "#76b28f" })
hi("@punctuation.delimiter",       { fg = "#76b28f" })
hi("@type",                        { fg = "#76b28f" })
hi("@type.builtin",                { fg = "#76b28f" })
hi("@constant",                    { fg = "#76b28f" })
hi("@constant.builtin",            { fg = "#76b28f" })
hi("@attribute",                   { fg = "#b07bc4" })
hi("@property",                    { fg = "#76b28f" })
hi("@field",                       { fg = "#76b28f" })
hi("@namespace",                   { fg = "#76b28f" })

vim.opt.cursorline = true
