
bind - split-window -v
bind | split-window -h

set-option -sg escape-time 10
set-option -g focus-events on
set-option -a terminal-features 'xterm-256color:RGB'

set -g history-limit 10000
set -g allow-rename off

set -g status-bg "#26A269" 
set -g status-fg "#000000"

# set -g status-style "bg=#303841,fg=#d8dee9"


bind-key j command-prompt -p "join pain from:" "join-pane -s '%%'"
bind-key s command-prompt -p "send pane to:" "join-pane -t '%%'"
bind-key C send-keys " | xclip -selection clipboard"

set-window-option -g mode-keys vi

set -g base-index 1
# TPM (TMUX PLUGIN MANAGER)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-copycat'

# tmux-copycat removed — use built-in search (/) in copy mode instead

set -g @logging-key "P"
set -g @logging-key-end "L"
set -g @logging-path "~/tmux_logs/"


run '~/.tmux/plugins/tpm/tpm'
